* [#A] LinkedIn Community Engagment          :IMPORTANT:
Ask the Right questions in a suitable question
- Principle: No matter you post or comment, make sure it add values to your audience
- Values: 得到开心, 解决问题, 得到治愈

- Principle: Boostbluffing < Talk < Listen < Learn
- Principle: Fake won't work. You have to be real and serious.
- Principle: When you reshare others' update, add value
- Principle: Talk just like face-to-face
- Add comments, instead of likes: It helps to promote yourself
- short sentence win

说话时埋坑，让对方有常规套路来互动

For me:
- Get feedbacks for technical details; Get *the direction or trends* for the tech community
** #  --8<-------------------------- separator ------------------------>8--
** TODO Add Summary at the end of the discussion: for yourself and for the community
- Only summarize popular discussions: 20+ comments
- Only summarize constructive discussions: something you've learned

- [Tool Popularity]
- [Impressive Input]
*** example
Guys, My Discussion Summary:

1. [Tool Popularity] Both nginx and haproxy are used quite a lot. AWS ELB and docker Consul are rising stars.

2. People tend to use nginx as RB(reverse proxy) and haproxy as LB(Load balancer)

3. [Impressive Input] Scott Hutchinson, Pradeep Chhetri, Chris Ciborowski

Many thanks for everyone!

https://www.linkedin.com/feed/update/urn:li:activity:6288957536393588736/
** #  --8<-------------------------- separator ------------------------>8--
** Routine tasks
- Linkedin send invitation for whoever likes or comments with your discussion: Not everyone in Linkedin are active
- Send out freechat to close LinkedIn friends regularly
** Start a topic
- Principle: as long as people want to say something, and easy to chimp in mind
- Start with a real story from yourself: it's ok to make fun of yourself, as long as it's real
- Start with an easy and open question: either useful or funny
- Explain your question in a simple and easy-to-understand way: People are careless and biasd
** Mindset
- Treat every audience as a respectful professional
** How to reply
- Speak out people's name, and speak with due respect!
** Maintain a topic
- 第一句话，要抓人眼球
- Avoid getting people distracted from your original topic
- 自己不容否认的便利，是抵lai不掉的
- 人都有逆反心理
- Add a recap after 3 days: summarize the discussions
** Build connections from discussion
- Add connections and endorsement from Linkedin Discussions
** DONE [#A] linkedin use emoji icon: https://www.linkedin.com/pulse/add-emoji-your-linkedin-profile-simple-copy-paste-brynne-tillman
   CLOSED: [2017-07-19 Wed 15:55]
https://www.linkedin.com/pulse/add-emoji-your-linkedin-profile-simple-copy-paste-brynne-tillman
https://www.linkedin.com/pulse/how-add-emojis-your-linkedin-profile-posts-john-nemo
** TODO [#A] Help others to solve questions they have posted: ask recommendations, if it's a good timing
