#+TAGS: noexport(n)
#+AUTHOR: dennyzhang.com (contact@dennyzhang.com)
* Grow Influence In LinkedIn
Ask the Right questions in a suitable question
- Principle: No matter you post or comment, make sure it add values to your audience

- Principle: Boostbluffing < Talk < Listen < Learn
- Principle: Fake won't work. You have to be real and serious.
- Principle: When you reshare others' update, add value
- Principle: Talk just like face-to-face
- Add comments, instead of likes: It helps to promote yourself
- short sentence win

For me:
- Get feedbacks for technical details; Get *the direction or trends* for the tech community
** Routine tasks
- Linkedin send invitation for whoever likes or comments with your discussion: Not everyone in Linkedin are active
- Send out freechat to close LinkedIn friends regularly
** Start a topic
- Principle: as long as people want to say something, and easy to chimp in mind
- Start with a real story from yourself: it's ok to make fun of yourself, as long as it's real
- Start with an easy and open question: either useful or funny
- Explain your question in a simple and easy-to-understand way: People are careless and biasd
** Mindset
- Treat every audience as a respectful professional
** How To reply
- Speak out people's name, and speak with due respect!
** Maintain A Topic
- Avoid getting people distracted from your original topic
- Add a recap after 3 days: summarize the discussions
** Build Connections From Discussions
- Add connections and endorsement from Linkedin Discussions
** LinkedIn Tips
*** linkedin use emoji icons
https://www.linkedin.com/pulse/add-emoji-your-linkedin-profile-simple-copy-paste-brynne-tillman
https://www.linkedin.com/pulse/how-add-emojis-your-linkedin-profile-posts-john-nemo
** #  --8<-------------------------- separator ------------------------>8-- :noexport:
** TODO [#A] Help others to solve questions they have posted: ask recommendations, if it's a good timing
** TODO Add Summary at the end of the discussion: for yourself and for the community
- Only summarize popular discussions: 20+ comments
- Only summarize constructive discussions: something you've learned

- [Tool Popularity]
- [Impressive Input]
*** example
Guys, My Discussion Summary:

1. [Tool Popularity] Both nginx and haproxy are used quite a lot. AWS ELB and docker Consul are rising stars.

2. People tend to use nginx as RB(reverse proxy) and haproxy as LB(Load balancer)

3. [Impressive Input] Scott Hutchinson, Pradeep Chhetri, Chris Ciborowski

Many thanks for everyone!

https://www.linkedin.com/feed/update/urn:li:activity:6288957536393588736/
** misc                                                                   :noexport:
*** 说话时埋坑，让对方有常规套路来互动
*** Values: 得到开心, 解决问题, 得到治愈
** chinese principle                                               :noexport:
- 第一句话，要抓人眼球
- 自己不容否认的便利，是抵lai不掉的
- 人都有逆反心理

